apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox-deployment
  namespace: homebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
        app: homebox
    spec:
      containers:
        - name: homebox
          image: ghcr.io/hay-kot/homebox:v0.10.3
          envFrom:
            - configMapRef:
                name: homebox-configmap
          volumeMounts:
            - mountPath: /data
              name: homebox-volume
          ports:
            - containerPort: 7745
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

      volumes:
        - name: homebox-volume
          persistentVolumeClaim:
            claimName: homebox-pvc
